In [ ]:
(1).

In [159]:
import pandas as pd
import numpy as np

In [160]:
df = pd.read_csv('youtube_dislike_dataset.csv')
df.head()

,video_id,title,channel_id,channel_title,published_at,view_count,likes,dislikes,comment_count,tags,description,comments
0,--0bCF-iK2E,Jadon Sancho Magical Skills & Goals,UC6UL29enLNe4mqwTfAyeNuw,Bundesliga,2021-07-01 10:00:00,1048888,19515,226,1319,football soccer ftbol alemn Bundesliga season ...,Enjoy the best skills and goals from Jadon San...,"Respect to Dortmund fans,must be sad losing hi..."
1,--14w5SOEUs,Migos - Avalanche (Official Video),UCGIelM2Dj3zza3xyV3pL3WQ,MigosVEVO,2021-06-10 16:00:00,15352638,359277,7479,18729,Migos Avalanche Quality Control Music/Motown R...,"Watch the the official video for Migos - ""Aval...",Migos just makes me want to live my live to th...
2,--40TEbZ9Is,Supporting Actress in a Comedy: 73rd Emmys,UClBKH8yZRcM4AsRjDVEdjMg,Television Academy,2021-09-20 01:03:32,925281,11212,401,831,,Hannah Waddingham wins the Emmy for Supporting...,Hannah's energy bursts through any screen. Wel...
3,--4tfbSyYDE,JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO,UCsmXiDP8S40uBeJYxvyulmA,JO1,2021-03-03 10:00:17,2641597,39131,441,3745,PRODUCE101JAPAN JO1 TheSTAR STA...,JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...,youngVer>< REN is really PERFECT. It's not ju...
4,--DKkzWVh-E,Why Retaining Walls Collapse,UCMOqf8ab-42UUQIdVoKwjlQ,Practical Engineering,2021-12-07 13:00:00,715724,32887,367,1067,retaining wall New Jersey highway Direct Conne...,One of the most important (and innocuous) part...,Keep up with all my projects here: https://pr...

In [161]:
df.tail()

,video_id,title,channel_id,channel_title,published_at,view_count,likes,dislikes,comment_count,tags,description,comments
37417,zzd4ydafGR0,Lil Tjay - Calling My Phone (feat. 6LACK) [Off...,UCEB4a5o_6KfjxHwNMnmj54Q,Lil Tjay,2021-02-12 05:03:49,120408275,2180780,35871,81360,Lil Tjay Steady Calling My Phone Calling My Ph...,"Official video for ""Calling My Phone"" by Lil T...",'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...
37418,zziBybeSAtw,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,UCWJ2lWNubArHWmf3FIHbfcQ,NBA,2021-01-16 05:39:05,2841917,20759,1049,2624,NBA G League Basketball game-0022000187 Lakers...,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,Montrezl Harrell is going crazy with the rebou...
37419,zzk09ESX7e0,[MV] (MAMAMOO) - Where Are We Now,UCuhAUMLzJxlP1W7mEk0_6lA,MAMAMOO,2021-06-02 09:00:10,13346678,720854,4426,90616,MAMAMOO WAW WAW MAMAMOO WAW Where Are We Now...,[MV] (MAMAMOO) - Where Are We Now\n\nInstagra...,I honestly do not know why this song hit so ha...
37420,zzmQEb0Em5I,FELLIPE ESCUDERO- Master Podcast #12,UC8NjnNWMsRqq11NYvHAQb1g,Master Podcast,2020-10-20 20:59:30,252057,19198,1234,1471,master masterpodcast lord lord vinheteiro z z ...,DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...,Foi um prazer passar esta tarde com vocs debat...
37421,zzxPZwaA-8w,Gareth Bale brace secures dramatic comeback on...,UCEg25rdRZXg32iwai6N6l0w,Tottenham Hotspur,2021-05-23 21:00:31,2252090,34063,868,2004,Spurs Tottenham Hotspur Tottenham Leicester ...,Two minute highlights from Tottenham Hotspur's...,Thank you Kane for everything you have given t...

In [ ]:
(2).

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37422 entries, 0 to 37421
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   video_id       37422 non-null  object
 1   title          37422 non-null  object
 2   channel_id     37422 non-null  object
 3   channel_title  37422 non-null  object
 4   published_at   37422 non-null  object
 5   view_count     37422 non-null  int64
 6   likes          37422 non-null  int64
 7   dislikes       37422 non-null  int64
 8   comment_count  37422 non-null  int64
 9   tags           37422 non-null  object
 10  description    37422 non-null  object
 11  comments       37264 non-null  object
dtypes: int64(4), object(8)
memory usage: 3.4+ MB

In [163]:
df.shape

(37422, 12)

In [ ]:
(3).

In [164]:
df.isnull().sum()/len(df)*100

video_id         0.000000
title            0.000000
channel_id       0.000000
channel_title    0.000000
published_at     0.000000
view_count       0.000000
likes            0.000000
dislikes         0.000000
comment_count    0.000000
tags             0.000000
description      0.000000
comments         0.422212
dtype: float64

In [165]:
df.isnull().sum().comments

158

In [166]:
df = df.dropna()
df

,video_id,title,channel_id,channel_title,published_at,view_count,likes,dislikes,comment_count,tags,description,comments
0,--0bCF-iK2E,Jadon Sancho Magical Skills & Goals,UC6UL29enLNe4mqwTfAyeNuw,Bundesliga,2021-07-01 10:00:00,1048888,19515,226,1319,football soccer ftbol alemn Bundesliga season ...,Enjoy the best skills and goals from Jadon San...,"Respect to Dortmund fans,must be sad losing hi..."
1,--14w5SOEUs,Migos - Avalanche (Official Video),UCGIelM2Dj3zza3xyV3pL3WQ,MigosVEVO,2021-06-10 16:00:00,15352638,359277,7479,18729,Migos Avalanche Quality Control Music/Motown R...,"Watch the the official video for Migos - ""Aval...",Migos just makes me want to live my live to th...
2,--40TEbZ9Is,Supporting Actress in a Comedy: 73rd Emmys,UClBKH8yZRcM4AsRjDVEdjMg,Television Academy,2021-09-20 01:03:32,925281,11212,401,831,,Hannah Waddingham wins the Emmy for Supporting...,Hannah's energy bursts through any screen. Wel...
3,--4tfbSyYDE,JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO,UCsmXiDP8S40uBeJYxvyulmA,JO1,2021-03-03 10:00:17,2641597,39131,441,3745,PRODUCE101JAPAN JO1 TheSTAR STA...,JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...,youngVer>< REN is really PERFECT. It's not ju...
4,--DKkzWVh-E,Why Retaining Walls Collapse,UCMOqf8ab-42UUQIdVoKwjlQ,Practical Engineering,2021-12-07 13:00:00,715724,32887,367,1067,retaining wall New Jersey highway Direct Conne...,One of the most important (and innocuous) part...,Keep up with all my projects here: https://pr...
...,...,...,...,...,...,...,...,...,...,...,...,...
37417,zzd4ydafGR0,Lil Tjay - Calling My Phone (feat. 6LACK) [Off...,UCEB4a5o_6KfjxHwNMnmj54Q,Lil Tjay,2021-02-12 05:03:49,120408275,2180780,35871,81360,Lil Tjay Steady Calling My Phone Calling My Ph...,"Official video for ""Calling My Phone"" by Lil T...",'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...
37418,zziBybeSAtw,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,UCWJ2lWNubArHWmf3FIHbfcQ,NBA,2021-01-16 05:39:05,2841917,20759,1049,2624,NBA G League Basketball game-0022000187 Lakers...,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,Montrezl Harrell is going crazy with the rebou...
37419,zzk09ESX7e0,[MV] (MAMAMOO) - Where Are We Now,UCuhAUMLzJxlP1W7mEk0_6lA,MAMAMOO,2021-06-02 09:00:10,13346678,720854,4426,90616,MAMAMOO WAW WAW MAMAMOO WAW Where Are We Now...,[MV] (MAMAMOO) - Where Are We Now\n\nInstagra...,I honestly do not know why this song hit so ha...
37420,zzmQEb0Em5I,FELLIPE ESCUDERO- Master Podcast #12,UC8NjnNWMsRqq11NYvHAQb1g,Master Podcast,2020-10-20 20:59:30,252057,19198,1234,1471,master masterpodcast lord lord vinheteiro z z ...,DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...,Foi um prazer passar esta tarde com vocs debat...
37421,zzxPZwaA-8w,Gareth Bale brace secures dramatic comeback on...,UCEg25rdRZXg32iwai6N6l0w,Tottenham Hotspur,2021-05-23 21:00:31,2252090,34063,868,2004,Spurs Tottenham Hotspur Tottenham Leicester ...,Two minute highlights from Tottenham Hotspur's...,Thank you Kane for everything you have given t...

In [ ]:
(4).

In [167]:
df.describe() #numerical_column

         view_count         likes      dislikes  comment_count
count  3.726400e+04  3.726400e+04  3.726400e+04   3.726400e+04
mean   5.710821e+06  1.672867e+05  4.996434e+03   9.966953e+03
std    2.431304e+07  5.384931e+05  3.075194e+04   1.173465e+05
min    2.036800e+04  2.200000e+01  3.000000e+00   1.000000e+00
25%    5.141305e+05  1.331725e+04  2.827500e+02   9.140000e+02
50%    1.321860e+06  4.255600e+04  7.980000e+02   2.347000e+03
75%    3.674527e+06  1.309665e+05  2.466250e+03   6.212000e+03
max    1.322797e+09  3.183768e+07  2.397733e+06   1.607103e+07

In [168]:
df.describe(include="object")   #categorical_column

,video_id,title,channel_id,channel_title,published_at,tags,description,comments
count,37264,37264,37264,37264,37264,37264,37264,37264
unique,37264,36958,10891,10813,36617,28705,35479,37264
top,--0bCF-iK2E,www,UCNAf1k0yIjyGu3k9BwAg3lg,Sky Sports Football,2020-10-16 04:00:10,,,"Respect to Dortmund fans,must be sad losing hi..."
freq,1,21,533,533,6,3808,587,1

In [ ]:
(5).

In [169]:
df.dtypes

video_id         object
title            object
channel_id       object
channel_title    object
published_at     object
view_count        int64
likes             int64
dislikes          int64
comment_count     int64
tags             object
description      object
comments         object
dtype: object

In [170]:
df['published_at'] = pd.to_datetime(df['published_at'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37264 entries, 0 to 37421
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   video_id       37264 non-null  object
 1   title          37264 non-null  object
 2   channel_id     37264 non-null  object
 3   channel_title  37264 non-null  object
 4   published_at   37264 non-null  datetime64[ns]
 5   view_count     37264 non-null  int64
 6   likes          37264 non-null  int64
 7   dislikes       37264 non-null  int64
 8   comment_count  37264 non-null  int64
 9   tags           37264 non-null  object
 10  description    37264 non-null  object
 11  comments       37264 non-null  object
dtypes: datetime64[ns](1), int64(4), object(7)
memory usage: 3.7+ MB

In [ ]:
(6).

In [202]:
df['published_month_no'] = df['published_at'].dt.month
df['published_month_no']

0         7
1         6
2         9
3         3
4        12
         ..
37417     2
37418     1
37419     6
37420    10
37421     5
Name: published_month_no, Length: 37264, dtype: int32

In [ ]:
(7).

In [172]:
df['published_month'] = df['published_at'].dt.strftime('%b')
df

,video_id,title,channel_id,channel_title,published_at,view_count,likes,dislikes,comment_count,tags,description,comments,published_month_no,published_month
0,--0bCF-iK2E,Jadon Sancho Magical Skills & Goals,UC6UL29enLNe4mqwTfAyeNuw,Bundesliga,2021-07-01 10:00:00,1048888,19515,226,1319,football soccer ftbol alemn Bundesliga season ...,Enjoy the best skills and goals from Jadon San...,"Respect to Dortmund fans,must be sad losing hi...",7,Jul
1,--14w5SOEUs,Migos - Avalanche (Official Video),UCGIelM2Dj3zza3xyV3pL3WQ,MigosVEVO,2021-06-10 16:00:00,15352638,359277,7479,18729,Migos Avalanche Quality Control Music/Motown R...,"Watch the the official video for Migos - ""Aval...",Migos just makes me want to live my live to th...,6,Jun
2,--40TEbZ9Is,Supporting Actress in a Comedy: 73rd Emmys,UClBKH8yZRcM4AsRjDVEdjMg,Television Academy,2021-09-20 01:03:32,925281,11212,401,831,,Hannah Waddingham wins the Emmy for Supporting...,Hannah's energy bursts through any screen. Wel...,9,Sep
3,--4tfbSyYDE,JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO,UCsmXiDP8S40uBeJYxvyulmA,JO1,2021-03-03 10:00:17,2641597,39131,441,3745,PRODUCE101JAPAN JO1 TheSTAR STA...,JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...,youngVer>< REN is really PERFECT. It's not ju...,3,Mar
4,--DKkzWVh-E,Why Retaining Walls Collapse,UCMOqf8ab-42UUQIdVoKwjlQ,Practical Engineering,2021-12-07 13:00:00,715724,32887,367,1067,retaining wall New Jersey highway Direct Conne...,One of the most important (and innocuous) part...,Keep up with all my projects here: https://pr...,12,Dec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37417,zzd4ydafGR0,Lil Tjay - Calling My Phone (feat. 6LACK) [Off...,UCEB4a5o_6KfjxHwNMnmj54Q,Lil Tjay,2021-02-12 05:03:49,120408275,2180780,35871,81360,Lil Tjay Steady Calling My Phone Calling My Ph...,"Official video for ""Calling My Phone"" by Lil T...",'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,2,Feb
37418,zziBybeSAtw,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,UCWJ2lWNubArHWmf3FIHbfcQ,NBA,2021-01-16 05:39:05,2841917,20759,1049,2624,NBA G League Basketball game-0022000187 Lakers...,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,Montrezl Harrell is going crazy with the rebou...,1,Jan
37419,zzk09ESX7e0,[MV] (MAMAMOO) - Where Are We Now,UCuhAUMLzJxlP1W7mEk0_6lA,MAMAMOO,2021-06-02 09:00:10,13346678,720854,4426,90616,MAMAMOO WAW WAW MAMAMOO WAW Where Are We Now...,[MV] (MAMAMOO) - Where Are We Now\n\nInstagra...,I honestly do not know why this song hit so ha...,6,Jun
37420,zzmQEb0Em5I,FELLIPE ESCUDERO- Master Podcast #12,UC8NjnNWMsRqq11NYvHAQb1g,Master Podcast,2020-10-20 20:59:30,252057,19198,1234,1471,master masterpodcast lord lord vinheteiro z z ...,DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...,Foi um prazer passar esta tarde com vocs debat...,10,Oct
37421,zzxPZwaA-8w,Gareth Bale brace secures dramatic comeback on...,UCEg25rdRZXg32iwai6N6l0w,Tottenham Hotspur,2021-05-23 21:00:31,2252090,34063,868,2004,Spurs Tottenham Hotspur Tottenham Leicester ...,Two minute highlights from Tottenham Hotspur's...,Thank you Kane for everything you have given t...,5,May

In [ ]:
(8).

In [173]:
df.groupby('published_month')['published_month_no'].size().to_frame().reset_index().sort_values(by='published_month_no',ascending=False)

   published_month  published_month_no
10             Oct                4976
11             Sep                4854
9              Nov                4821
1              Aug                4250
2              Dec                3063
5              Jul                2331
6              Jun                2305
7              Mar                2248
3              Feb                2125
0              Apr                2119
4              Jan                2099
8              May                2073

In [ ]:
(9).

In [174]:
df['video_id'].nunique()

37264

In [175]:
df['channel_id'].nunique()

10891

In [176]:
df['channel_title'].nunique()

10813

In [177]:
df.nunique()

video_id              37264
title                 36958
channel_id            10891
channel_title         10813
published_at          36617
view_count            37100
likes                 32509
dislikes               9038
comment_count         13163
tags                  28705
description           35479
comments              37264
published_month_no       12
published_month          12
dtype: int64

In [ ]:
(10).

In [178]:
channel_videocounts = df.groupby('channel_title').size().reset_index(name='video_counts')
channel_videocounts=channel_videocounts.sort_values(by='video_counts',ascending=False)
channel_videocounts.head(10)

            channel_title  video_counts
8223  Sky Sports Football           533
9098     The United Stand           301
1085             BT Sport           246
6310                  NBA           209
6347                  NFL           162
9780                  WWE           122
7809         SSSniperWolf            99
7810              SSundee            98
3037            FORMULA 1            87
6352                  NHL            86

In [179]:
channel_videocounts.tail(10)

         channel_title  video_counts
4790     Karikku Tuned             1
4787   Karen Bustillos             1
4786    Karen Aslanyan             1
4785           Karchez             1
4784     Karate Combat             1
4782      Kaptain Kuba             1
4777        Kanye West             1
4776    Kannur kitchen             1
4775    Kannada Cinema             1
10812             zoom             1

In [ ]:
(11).

In [180]:
df.groupby('title')['likes'].sum().to_frame().reset_index().sort_values(by='likes',ascending=False)

                                                 title     likes
5233                     BTS () 'Dynamite' Official MV  31837675
5228                       BTS () 'Butter' Official MV  20649409
5065   BLACKPINK - 'Ice Cream (with Selena Gomez)' M/V  17864527
5242                 BTS () 'Life Goes On' Official MV  16354127
5247          BTS () 'Permission to Dance' Official MV  15449003
...                                                ...       ...
33232        Virtual Pub Quiz, Live! Thursday 8th July       106
33189   Virtual Pub Quiz, Live! Saturday 12th December        97
28358                 Small Business Loans from OnDeck        29
31674           Tims For Good: A Taste Of The Familiar        28
19316                    Leading the Charge | Circle K        22

[36958 rows x 2 columns]

In [181]:
max_likes_index = df['likes'].idxmax()
min_likes_index = df['likes'].idxmin()
max_likes_title = df.loc[max_likes_index,'title']
min_likes_title = df.loc[min_likes_index,'title']
print(max_likes_title)
print(min_likes_title)

BTS () 'Dynamite' Official MV
Leading the Charge | Circle K

In [ ]:
(12).

In [182]:
df.groupby('title')['dislikes'].sum().to_frame().reset_index().sort_values(by='dislikes',ascending=False)

                                                   title  dislikes
8241                 Cuties | Official Trailer | Netflix   2397733
5233                       BTS () 'Dynamite' Official MV   1814333
7252   Cardi B - WAP feat. Megan Thee Stallion [Offic...   1331181
2926   52 GAJ KA DAMAN | PRANJAL DAHIYA | AMAN JAJI |...   1259533
5065     BLACKPINK - 'Ice Cream (with Selena Gomez)' M/V   1253187
...                                                  ...       ...
19361  Leicester v Gloucester | Wigglesworth Impresse...         7
35170  YONEX Thailand Open | Day 3: Saina Nehwal (IND...         7
19334  Leeds Rhinos vs Wakefield Trinity | Super Leag...         6
19777  Live Stream: Hampshire v Yorkshire - LV= Count...         4
31674             Tims For Good: A Taste Of The Familiar         3

[36958 rows x 2 columns]

In [183]:
max_dislikes_index = df['dislikes'].idxmax()
min_dislikes_index = df['dislikes'].idxmin()
max_dislikes_title = df.loc[max_dislikes_index,'title']
min_dislikes_title = df.loc[min_dislikes_index,'title']
print(max_dislikes_title)
print(min_dislikes_title)

Cuties | Official Trailer | Netflix
Tims For Good: A Taste Of The Familiar

In [ ]:
(14).

In [195]:
january_videos = df[df['published_at'].dt.month == 1]
january_videos

,video_id,title,channel_id,channel_title,published_at,view_count,likes,dislikes,comment_count,tags,description,comments,published_month_no,published_month
27,-2Gwm7QfBnE,Q&A With Naisha,UCYwNMbogQFzMccPSuy-pPWg,MianTwins,2021-01-21 00:05:47,872372,38626,239,621,,Hey Guys!!! this has been the most requested v...,I feel like Nate and Aishas personality match ...,1,Jan
48,-4sfXSHSxzA,SURPRISING BRENT WITH HIS TIKTOK CRUSH!!,UCPpATKqmMV-CNRNWYaDUwiA,Alexa Rivera,2021-01-16 21:40:04,6504784,262477,5779,7907,,He had no idea! Thank you guys so much for wat...,Thank you guys for watching and don't forget t...,1,Jan
95,-AJD1Fc5rpQ,WE ARE HAVING A BABY! | finding out i'm pregna...,UCVsTboAhpnuL6j-tDePvNwQ,Tess Christine,2021-01-03 21:53:48,533084,38965,119,1650,,I am so happy to tell you that I am pregnant!!...,Okay I needed a moment to collect my thoughts ...,1,Jan
103,-AuJiwjsmWk,Do Ugly Foods Taste Worse? Taste Test,UCzpCc5n9hqiVC7HhPwcIKEg,Good Mythical MORE,2021-01-19 11:00:01,1057077,22526,531,773,gmm good mythical morning rhettandlink rhett a...,"Today, we're doing a blind taste test to deter...","""there's nothing wrong with it being bent""\nI ...",1,Jan
182,-JhqO2KWr5U,Schlatt gets fit,UCWZp4y1jqBuvLtiyxSs_ZBw,Big guy,2021-01-24 22:50:57,1724965,119431,325,1578,jschlatt big guy jschlatt highlights schlatt j...,#jschlatt #schlatt #bigguy #short,Schlatt is single handedly wiping out all the ...,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37300,zmzFL5bG-jc,DEVINE MON PERSONNAGE AVANT AKINATOR ! (c'est ...,UCIlr3byh6wmXgcPx_Tm9Ocw,Piwerre,2021-01-16 16:12:19,670357,54462,832,1249,Piwerre frere de michou crouton among us devin...,Discord Piwerre : https://discord.gg/QBduPgAA...,Mdr michou quand c'est pas ses tournage il fou...,1,Jan
37329,zpzjex7qwrA,Lampard Sacked Within Days Rorys Misery | Chel...,UCkD-ZOixI0a9FjIExDsHsbg,The Kick Off,2021-01-03 20:13:49,428646,12060,296,1505,Premier league Chelsea chelsea 1-3 Man City Ch...,The Kick Off watched Manchester City destroy C...,True Its like a fighter who Geordie But I thou...,1,Jan
37345,zqyv-B6mnBM,Lil Wayne - Ain't Got Time (Audio),UCO9zJy7HWrIS3ojB4Lr7Yqw,Lil Wayne,2021-01-21 05:00:10,2238244,58925,2365,5539,lil wayne weezy weezy wednesday wayne carter y...,"Official audio for Lil Wayne ""Ain't Got Time"",...","RIP Juice Wrld, wrote that on two cups, pour o...",1,Jan
37383,zwfu1-24T7Q,PRADA Cup Day 1 | Full Race Replay | PRADA Cup...,UCo15ZYO_XDRU9LI30OPtxAg,America's Cup,2021-01-15 04:07:55,317382,2008,83,192,America's Cup Americas Cup AC36 AC75 Presented...,"The opening day of the PRADA Cup in Auckland, ...",Incredible how these boats evolve in a short t...,1,Jan
37418,zziBybeSAtw,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,UCWJ2lWNubArHWmf3FIHbfcQ,NBA,2021-01-16 05:39:05,2841917,20759,1049,2624,NBA G League Basketball game-0022000187 Lakers...,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,Montrezl Harrell is going crazy with the rebou...,1,Jan

In [201]:
len(january_videos)

2099